### PR TITLE
Fix the failing tests & installation issue in Python 3.4

### PR DESCRIPTION
**Pull request by seratch**
This pull request updates the failing tests and brings the TravisCI builds to normal.

### CODE REVIEW

**Comment by seratch** [comment]
Specifically, the build settings for Python 3.4 has another issue on account of `readme_renderer` installation failure. I've updated TravisCI build settings for it in another commit.

It seems that the CI build is successful with the changes in this PR 🎉

**Comment by seratch** [comment]
Hi @engn33r, I am glad to see you started actively working on this project 🎉 As you may be aware of, the CI builds for this project have been failing for a while. To make future contributions easier, could you check this out if you have a chance? Please let me know if you want something changed in this PR.

**Comment by engn33r** [comment]
Thanks, much appreciated!

**Comment by seratch** [comment]
@engn33r Thanks for merging! The latest revision has the following test failure. It did not exist when I was working on this PR. Probably, other changes brought this.

```
======================================================================
FAIL: testWsUtils (websocket.tests.test_websocket.WebSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/websocket-client/websocket-client/websocket/tests/test_websocket.py", line 223, in testWsUtils
    self.assertEqual(_validate_header(header, key, ["Sub1", "suB2"]), (True, "sub1"))
AssertionError: Tuples differ: (True, 'sUb1') != (True, 'sub1')
First differing element 1:
'sUb1'
'sub1'
- (True, 'sUb1')
?          ^
+ (True, 'sub1')
?          ^
----------------------------------------------------------------------
Ran 32 tests in 8.271s
FAILED (failures=1)
```

**Comment by engn33r** [comment]
Yes, I was looking into this. Your PR fixed most of the build, and I think this is a new error. The message `Invalid or duplicate subprotocol` made me think the issue might be from the change I introduced in commit e71edd3, or perhaps from commit c9093d0. I'll look at this more closely later with fresh eyes, but if you want to try a pull request reverting some of these changes, I think we can fix this very soon.

**Pull request merged**
