### PR TITLE
Use `thread.is_alive` as `isAlive` is deprecated

### PR DESCRIPTION
**Pull request by itaisteinherz**

### CODE REVIEW

**Comment by itaisteinherz** [comment]
@liris It would be great if you could take a look at this :)

**Comment by mikeage** [comment]
Note that this has been available since Python 2.7, so it's fully backwards compatible

**Comment by seratch** [comment]
@engn33r I know you have been busy for checking many issues now but could you check this one if you have a chance? It'd be greatly appreciated if we can have this change in the next release!

Currently, I have been seeing this warning every time I stop an app using this library. As already mentioned above, merging this is safe enough as it's compatible with any Python versions this project supports.

**Comment by engn33r** [comment]
Thanks @itaisteinherz @mikeage @seratch! All inputs are appreciated as we get this project back in shape

**Pull request merged**
