### PR TITLE
fix: pass correct number of arguments to logging function

### PR DESCRIPTION
**Pull request by ozichert**
As the wrong number of arguments is passed to the logging function there occured an error.

### CODE REVIEW

**Comment by engn33r** [comment]
I would prefer to update the code to use str.format() instead of the older % operator, in case % gets deprecated in the future. Can you edit the PR?

**Comment by ozichert** [comment]
@engn33r Just did this for the whole `_app.py` logging messages.

**Comment by engn33r** [comment]
Thanks for the PR. At some point a PR should be made (by me or someone else) to switch the other instances of % to str.format() for consistency

**Comment by engn33r** [comment]
Closing out this comment. I removed the modulo string formatting with % and replaced it with str.format() in https://github.com/websocket-client/websocket-client/commit/c6a445f2b98b4f80befcd5260da82d157e3fdabf

**Pull request merged**
