### PR TITLE
Add entry points

### PR DESCRIPTION
**Pull request by BastianZim**
Closes https://github.com/websocket-client/websocket-client/issues/756

This PR adds `entry_points` as defined in the issue. Additionally, the CLI tool is tested by running the help command as it is currently not tested.

Note: It might make sense to replace this with proper tests at some point.

### CODE REVIEW

**Comment by engn33r** [comment]
Thanks, this is definitely better than what I attempted. Currently CI is giving a `wsdump: command not found` error with the Ubuntu build process. I'll test this out locally later to see if I can recreate. I will also need to check why code coverage dropped 8.61%, but it's probably because wsdump.py was moved into the websocket/ directory.

**Comment by BastianZim** [comment]
> Currently CI is giving a wsdump: command not found error with the Ubuntu build process.

I think that's my bad. I didn't check if the package is actually installed which seems to not be the case. To be honest, running `-h` isn't a good test anyway so I think it'd be better to remove it again. The only reason I didn't put in a full test is that I'm not familiar enough with pytest to know how to test CLI commands. If you know more about that, please feel free to push to my branch directly.
The command works locally for me so it should be just about the tests, not the PR.

> I will also need to check why code coverage dropped 8.61%, but it's probably because wsdump.py was moved into the websocket/ directory.

Yeah, I think it's just the change of location. Previously, only websocket was included.

**Comment by BastianZim** [comment]
I have moved everything under the normal package and just made the setup slightly leaner, which should also make the tests easier.

Based on other packages I guess the easiest would be to call `subprocess.run()` in a test file with the CLI and test a couple of commands. What do you think?
I don't have any experience with unit tests as I usually use pytest but please feel free to push to my branch directly, if you have some ideas.

**Comment by engn33r** [comment]
I sent a PR to suggest two changes to fix the handling of GitHub Actions CI:
1. Test the wsdump.py script with `wsdump.py -h` (I tried `wsdump -h` but CI required the .py extension) right after websocket-client is installed. websocket-client currently doesn't get installed in the build.yml test, so I put this check in codecoverage.yml
2. Omit the wsdump.py script from code coverage because wsdump.py doesn't contribute any new functionality to the underlying websocket-client library. As long as the `wsdump.py -h` command doesn't trigger an error, the script should be installed. I'm not too concerned about code coverage for wsdump.py because most users of websocket-client are importing the library for custom purposes.

**Comment by BastianZim** [comment]
Ok makes all sense. Let's see if it works this time.

**Comment by engn33r** [comment]
Although the `wsdump.py -h` test worked when I ran it in the GitHub CI of a test fork yesterday, it is not working today. I am going to remove the wsdump.py test entirely from CI since it's not critical to the overall functionality of websocket-client as a library.

**Comment by engn33r** [comment]
CI is passing now. I will merge this PR after 1-2 days in case you have any comments or final edits

**Comment by BastianZim** [comment]
Ok, thanks. I'll just test this locally again as it's currently not tested at all - just to verify that everything's working as intended and then would post the result here.

**Comment by BastianZim** [comment]
Tested it locally and `wsdump -h` works, would be good to go from my side.

**Comment by engn33r** [comment]
Great, thanks for the PR!

**Comment by BastianZim** [comment]
Thanks for merging!

**Pull request merged**
