### PR TITLE
Adding typehints to _abnf.py

### LINKED ISSUE #749: FR: add type hint
Since this project requires python >= 3.6, it would be great if we could add type hint support.

### PR DESCRIPTION
**Pull request by RoryGlenn**
Adding typehints to _abnf.py.
This will be one of several commits to help resolve #749 and #684.
I will try to commit one file at a time for easier debugging and reviewing.

### CODE REVIEW

**Comment by engn33r** [comment]
Thank you, adding typehints is a very welcome addition! :+1:

The CI indicates these changes need some linting fixes and at least one test needs modification to run. I can take a look at what is needed if it would help, but don't have time this week.

**Comment by engn33r** [comment]
I wonder if the current build error of `TypeError: 'type' object is not subscriptable` for the line `def _is_no_proxy_host(hostname: str, no_proxy: list[str]) -> bool:` is only an issue on Python 3.8?  I wasn't able to recreate the issue in a quick local test with a more recent Python version, I'll dig into this deeper later.

**Comment by RoryGlenn** [comment]
Yes that is correct, python 3.8 does not allow nested type hints but 3.9 does. 
I'll submit a change this week

**Comment by engn33r** [comment]
All CI is passing, thanks for the upgrades :+1:

**Pull request merged**
