### PR TITLE
Update to use the selectors module with DefaultSelector

### LINKED ISSUE #561: filedescriptor out of range in select()
hi. what is this message "filedescriptor out of range in select()" I receive this error in on_error() function when I increase load on my server?

### PR DESCRIPTION
**Pull request by DaanVanVugt**
This works from python 3.4 onwards and provides the most efficient
implementation depending on the current platform.
https://docs.python.org/3/library/selectors.html#selectors.DefaultSelector

Would fix #561 

This is a naive implementation, it might be possible to keep the selectors around for a longer time to avoid rebuilding them on every listen.

### CODE REVIEW

**Comment by liris** [comment]
Travis failed to build. Could you check it?

**Comment by tmatth** [comment]
> Travis failed to build. Could you check it?

Travis is failing on the Python 2.7 job, which as @Exteris notes in the description, is expected as this will only work for Python >= 3.4

**Comment by indranilp** [comment]
This is still not available in master. Can you please check this?

**Comment by engn33r** [comment]
I will merge this soon, since the discussion in issue #660 shows that this project will soon focus on only supporting Python 3 without the need for backward compatibility for Python 2.

**Comment by engn33r** [comment]
Thanks for the PR!

**Comment by DaanVanVugt** [comment]
Thanks for merging!

**Pull request merged**
