### PR TITLE
Use poll rather than select.

### PR DESCRIPTION
**Pull request by dellis23**
select cannot select on file descriptor numbers > FD_SETSIZE (1024 on
most systems), limiting the number of connections that can be created.

### CODE REVIEW

**Comment by dellis23** [comment]
One of my esteemed colleagues noted that this does break compatibility with Windows if it is indeed intended to run there.  If so, I can do something to fall back to select.

**Comment by swordmaster2k** [comment]
Came across this issue today when trying to open 1000+ websockets for a load test it led to the exception:

_filedescriptor out of range in select()_

**Comment by dellis23** [comment]
Yeah that's the exact use case I had -- load testing.

**Comment by swordmaster2k** [comment]
Installing your branch through pip solved the issue I encountered for now. Hopefully this will be merged, just have to be careful on behavior on Windows platforms.

**Comment by dellis23** [comment]
Awesome, glad to hear that.  Thanks for posting the error message.  Hopefully that'll help googlers in the meantime.

**Comment by liris** [comment]
Does this work on Windows? I'm not sure because I don't have Windows.
Please let me know whether this works on Windows. If it works, I'll merge this

**Comment by swordmaster2k** [comment]
I've tested this on Windows and it does appear to break it I get the following error: module 'select' has no attribute 'poll'

I'm still using this branch myself, a fall back should be added for Windows OSes to use select instead.

**Comment by bubbleboy14** [comment]
Hey homies. Here's the solution: https://github.com/websocket-client/websocket-client/pull/375

**Comment by liris** [comment]
now we support dispatcher, which customize event poller/selector.

```python
class PollDispatcher
   def __init__(self):
        self.poller = select.poll()
        READ_FLAGS = (select.POLLIN | select.POLLPRI |
                                    select.POLLHUP | select.POLLERR)
        self.poller.register(self.sock.sock, READ_FLAGS)

    def read(self, sock, callback):
        while self.app.sock.connected:
            events = poller.poll(ping_timeout)
            if events:
                callback()

app = WebsocketApp(..., dipacher=PollDispacher())

```

**Pull request closed without merging**
